### ISSUE TITLE
Complete the GUI development to accommodate all the features

### ISSUE THREAD

**Issue by akurapati1** [roschlynnmichael/CSCI5300_Project#24]
This Issue is completely based on the front-end team. The GUI should be developed such that it is accommodating all the required fields and button required to execute all the features of the application. If needed discuss with the team and the developers who worked on the backend to understand all the needed fields on the front-end so that the User can get an idea about all the functionalities of the application. 

Due Date: Sprint 3

Acceptance Criteria: 

> The front-end must have all the buttons and fields to accommodate all the features and functionalities of the system. 

> As of buttons, mainly, Add expense, Add income, Add savings goal should be on the front end. 

> As of fields, text boxes should pop up or present in the front-end 

> Front-end may not be so appealing but should styled enough so that the user can clearly understand how to use the system for their budgeting.

**Comment by francina172000** [comment]
Updated code is in Branch Francina. Have a look and use that code!
